#!/usr/bin/env python3
"""
Export consistency-experiment summary.json into structured tabular outputs.

This script does NOT generate a narrative report. It creates CSV tables and
prints compact table previews in terminal.
"""

import argparse
import csv
import json
import math
import os
from statistics import mean, pstdev, stdev
from typing import Any, Dict, List


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Export consistency summary.json into CSV tables."
    )
    parser.add_argument(
        "--summary_json",
        type=str,
        default="results/consistency/injecagent_ds_first10/summary.json",
        help="Path to summary.json generated by run_consistency_injecagent_ds10.py",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default="",
        help="Directory to write CSV outputs. Defaults to <summary_json_dir>/tables",
    )
    return parser.parse_args()


def ensure_dir(path: str) -> None:
    os.makedirs(path, exist_ok=True)


def write_csv(path: str, rows: List[Dict[str, Any]], fieldnames: List[str]) -> None:
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def stability_label(success_count: int, num_runs: int) -> str:
    if success_count == num_runs:
        return "stable_success"
    if success_count == 0:
        return "stable_fail"
    return "unstable"


def build_jaccard_matrix(pairwise: List[Dict[str, Any]], num_runs: int) -> List[List[float]]:
    matrix = [[1.0 for _ in range(num_runs)] for _ in range(num_runs)]
    for p in pairwise:
        i = int(p["run_i"]) - 1
        j = int(p["run_j"]) - 1
        v = float(p["jaccard_success_set"])
        matrix[i][j] = v
        matrix[j][i] = v
    return matrix


def t_critical_95(df: int) -> float:
    """Two-sided 95% t critical value (small table + normal fallback)."""
    table = {
        1: 12.706,
        2: 4.303,
        3: 3.182,
        4: 2.776,
        5: 2.571,
        6: 2.447,
        7: 2.365,
        8: 2.306,
        9: 2.262,
        10: 2.228,
        11: 2.201,
        12: 2.179,
        13: 2.160,
        14: 2.145,
        15: 2.131,
        16: 2.120,
        17: 2.110,
        18: 2.101,
        19: 2.093,
        20: 2.086,
        21: 2.080,
        22: 2.074,
        23: 2.069,
        24: 2.064,
        25: 2.060,
        26: 2.056,
        27: 2.052,
        28: 2.048,
        29: 2.045,
        30: 2.042,
    }
    return table.get(df, 1.96)


def mean_ci_95_from_runs(values: List[float]) -> Dict[str, float]:
    n = len(values)
    m = mean(values) if values else 0.0
    if n <= 1:
        return {"mean": m, "lower": m, "upper": m, "half_width": 0.0}
    s = stdev(values)
    tcrit = t_critical_95(n - 1)
    half = tcrit * s / math.sqrt(n)
    return {"mean": m, "lower": m - half, "upper": m + half, "half_width": half}


def wilson_ci_95(successes: int, total: int) -> Dict[str, float]:
    if total <= 0:
        return {"p": 0.0, "lower": 0.0, "upper": 0.0}
    z = 1.96
    phat = successes / total
    denom = 1 + (z * z / total)
    center = (phat + (z * z) / (2 * total)) / denom
    margin = (z / denom) * math.sqrt((phat * (1 - phat) / total) + (z * z / (4 * total * total)))
    return {"p": phat, "lower": center - margin, "upper": center + margin}


def print_preview(title: str, rows: List[Dict[str, Any]], cols: List[str], limit: int = 12) -> None:
    print(f"\n== {title} ==")
    if not rows:
        print("(empty)")
        return
    show_rows = rows[:limit]
    widths = {c: max(len(c), *(len(str(r.get(c, ""))) for r in show_rows)) for c in cols}
    header = " | ".join(c.ljust(widths[c]) for c in cols)
    sep = "-+-".join("-" * widths[c] for c in cols)
    print(header)
    print(sep)
    for r in show_rows:
        print(" | ".join(str(r.get(c, "")).ljust(widths[c]) for c in cols))
    if len(rows) > limit:
        print(f"... ({len(rows) - limit} more rows)")


def export_tables(summary: Dict[str, Any], output_dir: str) -> Dict[str, str]:
    runs = summary.get("runs", [])
    aggregate = summary.get("aggregate", {})
    overall = aggregate.get("overall", {})

    if not runs:
        raise ValueError("summary.json contains no `runs` data.")

    num_runs = len(runs)
    num_cases = int(runs[0]["num_cases"])

    # Run-level table
    run_rows: List[Dict[str, Any]] = []
    asr_best_list: List[float] = []
    asr_last_list: List[float] = []
    asr_final_or_list: List[float] = []
    for r in runs:
        best_cases = [int(bool(x)) for x in r["best_success_by_case"]]
        last_cases = [int(bool(x)) for x in r["last_success_by_case"]]
        final_or_cases = [int(bool(b) or bool(l)) for b, l in zip(best_cases, last_cases)]
        row = {
            "run_index": int(r["run_index"]),
            "num_cases": int(r["num_cases"]),
            "asr_best": float(r["asr_best"]),
            "asr_last": float(r["asr_last"]),
            "asr_final_or": mean(final_or_cases) if final_or_cases else 0.0,
            "output_path": r["output_path"],
        }
        run_rows.append(row)
        asr_best_list.append(float(r["asr_best"]))
        asr_last_list.append(float(r["asr_last"]))
        asr_final_or_list.append(float(row["asr_final_or"]))
    run_rows.sort(key=lambda x: x["run_index"])

    # Case x run matrices
    case_best_rows: List[Dict[str, Any]] = []
    case_last_rows: List[Dict[str, Any]] = []
    case_final_or_rows: List[Dict[str, Any]] = []

    for c in range(num_cases):
        row_best: Dict[str, Any] = {"case_index": c}
        row_last: Dict[str, Any] = {"case_index": c}
        row_final_or: Dict[str, Any] = {"case_index": c}
        best_count = 0
        last_count = 0
        final_or_count = 0
        for r_idx, r in enumerate(run_rows, start=1):
            run_data = runs[r["run_index"] - 1]
            best_val = int(bool(run_data["best_success_by_case"][c]))
            last_val = int(bool(run_data["last_success_by_case"][c]))
            final_or_val = int(best_val or last_val)
            row_best[f"run_{r_idx}"] = best_val
            row_last[f"run_{r_idx}"] = last_val
            row_final_or[f"run_{r_idx}"] = final_or_val
            best_count += best_val
            last_count += last_val
            final_or_count += final_or_val
        row_best["success_count"] = best_count
        row_best["success_rate"] = best_count / num_runs
        row_best["stability_label"] = stability_label(best_count, num_runs)
        row_last["success_count"] = last_count
        row_last["success_rate"] = last_count / num_runs
        row_last["stability_label"] = stability_label(last_count, num_runs)
        row_final_or["success_count"] = final_or_count
        row_final_or["success_rate"] = final_or_count / num_runs
        row_final_or["stability_label"] = stability_label(final_or_count, num_runs)
        case_best_rows.append(row_best)
        case_last_rows.append(row_last)
        case_final_or_rows.append(row_final_or)

    # Case-level stats table
    agg_per_case = aggregate.get("per_case", [])
    case_stat_rows: List[Dict[str, Any]] = []
    for c in range(num_cases):
        agg_case = agg_per_case[c] if c < len(agg_per_case) else {}
        best_cnt = int(case_best_rows[c]["success_count"])
        last_cnt = int(case_last_rows[c]["success_count"])
        final_or_cnt = int(case_final_or_rows[c]["success_count"])
        case_stat_rows.append(
            {
                "case_index": c,
                "best_success_count": best_cnt,
                "best_success_rate": best_cnt / num_runs,
                "last_success_count": last_cnt,
                "last_success_rate": last_cnt / num_runs,
                "final_or_success_count": final_or_cnt,
                "final_or_success_rate": final_or_cnt / num_runs,
                "best_string_unique_count": int(agg_case.get("best_string_unique_count", 0)),
                "best_stability_label": stability_label(best_cnt, num_runs),
                "last_stability_label": stability_label(last_cnt, num_runs),
                "final_or_stability_label": stability_label(final_or_cnt, num_runs),
            }
        )

    # Pairwise jaccard and matrix
    pairwise = aggregate.get("pairwise_success_set_jaccard", [])
    pairwise_rows = [
        {
            "run_i": int(p["run_i"]),
            "run_j": int(p["run_j"]),
            "jaccard_success_set": float(p["jaccard_success_set"]),
        }
        for p in pairwise
    ]
    matrix = build_jaccard_matrix(pairwise_rows, num_runs)
    matrix_rows: List[Dict[str, Any]] = []
    for i in range(num_runs):
        row: Dict[str, Any] = {"run": f"run_{i + 1}"}
        for j in range(num_runs):
            row[f"run_{j + 1}"] = matrix[i][j]
        matrix_rows.append(row)

    # Overall table
    best_mean_ci = mean_ci_95_from_runs(asr_best_list)
    last_mean_ci = mean_ci_95_from_runs(asr_last_list)
    final_or_mean_ci = mean_ci_95_from_runs(asr_final_or_list)
    total_trials = num_runs * num_cases
    best_total_success = int(sum(r["success_count"] for r in case_best_rows))
    last_total_success = int(sum(r["success_count"] for r in case_last_rows))
    final_or_total_success = int(sum(r["success_count"] for r in case_final_or_rows))
    best_wilson = wilson_ci_95(best_total_success, total_trials)
    last_wilson = wilson_ci_95(last_total_success, total_trials)
    final_or_wilson = wilson_ci_95(final_or_total_success, total_trials)

    overall_row = {
        "num_runs": num_runs,
        "num_cases": num_cases,
        "mean_asr_best": float(overall.get("mean_asr_best", best_mean_ci["mean"])),
        "std_asr_best": float(overall.get("std_asr_best", pstdev(asr_best_list))),
        "mean_asr_last": float(overall.get("mean_asr_last", last_mean_ci["mean"])),
        "std_asr_last": float(overall.get("std_asr_last", pstdev(asr_last_list))),
        "mean_asr_final_or": float(overall.get("mean_asr_final_or", final_or_mean_ci["mean"])),
        "std_asr_final_or": float(overall.get("std_asr_final_or", pstdev(asr_final_or_list))),
        "ci95_mean_asr_best_lower": best_mean_ci["lower"],
        "ci95_mean_asr_best_upper": best_mean_ci["upper"],
        "ci95_mean_asr_last_lower": last_mean_ci["lower"],
        "ci95_mean_asr_last_upper": last_mean_ci["upper"],
        "ci95_mean_asr_final_or_lower": final_or_mean_ci["lower"],
        "ci95_mean_asr_final_or_upper": final_or_mean_ci["upper"],
        "pooled_total_trials": total_trials,
        "pooled_best_successes": best_total_success,
        "pooled_last_successes": last_total_success,
        "pooled_final_or_successes": final_or_total_success,
        "ci95_wilson_best_lower": best_wilson["lower"],
        "ci95_wilson_best_upper": best_wilson["upper"],
        "ci95_wilson_last_lower": last_wilson["lower"],
        "ci95_wilson_last_upper": last_wilson["upper"],
        "ci95_wilson_final_or_lower": final_or_wilson["lower"],
        "ci95_wilson_final_or_upper": final_or_wilson["upper"],
    }
    if pairwise_rows:
        vals = [float(p["jaccard_success_set"]) for p in pairwise_rows]
        overall_row["mean_pairwise_jaccard"] = mean(vals)
        overall_row["min_pairwise_jaccard"] = min(vals)
        overall_row["max_pairwise_jaccard"] = max(vals)
    else:
        overall_row["mean_pairwise_jaccard"] = 1.0
        overall_row["min_pairwise_jaccard"] = 1.0
        overall_row["max_pairwise_jaccard"] = 1.0

    # Write outputs
    ensure_dir(output_dir)

    paths = {
        "overall_metrics": os.path.join(output_dir, "overall_metrics.csv"),
        "run_metrics": os.path.join(output_dir, "run_metrics.csv"),
        "case_run_matrix_best": os.path.join(output_dir, "case_run_matrix_best.csv"),
        "case_run_matrix_last": os.path.join(output_dir, "case_run_matrix_last.csv"),
        "case_run_matrix_final_or": os.path.join(output_dir, "case_run_matrix_final_or.csv"),
        "case_stats": os.path.join(output_dir, "case_stats.csv"),
        "jaccard_pairs": os.path.join(output_dir, "jaccard_pairs.csv"),
        "jaccard_matrix": os.path.join(output_dir, "jaccard_matrix.csv"),
        "tables_manifest": os.path.join(output_dir, "tables_manifest.json"),
    }

    write_csv(paths["overall_metrics"], [overall_row], list(overall_row.keys()))
    write_csv(paths["run_metrics"], run_rows, ["run_index", "num_cases", "asr_best", "asr_last", "asr_final_or", "output_path"])

    best_fields = ["case_index"] + [f"run_{i}" for i in range(1, num_runs + 1)] + ["success_count", "success_rate", "stability_label"]
    write_csv(paths["case_run_matrix_best"], case_best_rows, best_fields)
    write_csv(paths["case_run_matrix_last"], case_last_rows, best_fields)
    write_csv(paths["case_run_matrix_final_or"], case_final_or_rows, best_fields)

    write_csv(
        paths["case_stats"],
        case_stat_rows,
        [
            "case_index",
            "best_success_count",
            "best_success_rate",
            "last_success_count",
            "last_success_rate",
            "final_or_success_count",
            "final_or_success_rate",
            "best_string_unique_count",
            "best_stability_label",
            "last_stability_label",
            "final_or_stability_label",
        ],
    )

    write_csv(paths["jaccard_pairs"], pairwise_rows, ["run_i", "run_j", "jaccard_success_set"])
    write_csv(paths["jaccard_matrix"], matrix_rows, ["run"] + [f"run_{i}" for i in range(1, num_runs + 1)])

    with open(paths["tables_manifest"], "w", encoding="utf-8") as f:
        json.dump(paths, f, indent=2, ensure_ascii=False)

    # Console preview (tabular, no narrative)
    print_preview("Run Metrics", run_rows, ["run_index", "num_cases", "asr_best", "asr_last", "asr_final_or"])
    print_preview(
        "Case x Run (best_success)",
        case_best_rows,
        ["case_index"] + [f"run_{i}" for i in range(1, num_runs + 1)] + ["success_count", "stability_label"],
    )
    print_preview(
        "Case Stats",
        case_stat_rows,
        [
            "case_index",
            "best_success_count",
            "last_success_count",
            "final_or_success_count",
            "best_string_unique_count",
            "final_or_stability_label",
        ],
    )

    return paths


def main() -> None:
    args = parse_args()

    summary_path = args.summary_json
    if not os.path.exists(summary_path):
        raise FileNotFoundError(f"summary_json not found: {summary_path}")

    with open(summary_path, "r", encoding="utf-8") as f:
        summary = json.load(f)

    output_dir = args.output_dir.strip() or os.path.join(os.path.dirname(summary_path), "tables")
    paths = export_tables(summary, output_dir)

    print("\n== Output Files ==")
    for k, v in paths.items():
        print(f"{k}: {v}")


if __name__ == "__main__":
    main()
